---
title: "def_project"
author: "곽명빈"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(dplyr)
library(stringr)
library(tidyr)
library(tidyverse)
```

# 데이터 읽기
```{r}
weather <- read.csv("기상데이터.csv")
city <- read.csv("city.csv")
city2 <- read.csv("행열전환city.csv")
#데이터 확인
head(city2)
head(weather)
```

#생산량, 면적당 생산량만 나타내게 처리
```{r}
production <- city2[, seq(from=4, to=796, by=3)] # 생산량

production2 <- city2[, seq(from=3, to=796, by=3)] # 면적당

day <- city2$행정구역별 # 날짜 데이터만 추출해서

production <- cbind(day, production) #붙이기
 
production2 <- cbind(day, production2) #붙이기
```

# 면적당 
```{r}
name <- gsub(".1", "", names(production2)) # 뒤에 붙은 .1 제거

colnames(production2) = c(name)  # 제거된 .1, .4로 변경

a <- gather(production2, key="day") # 한줄로 만들기

production2 <- cbind(day, a)
```

# 생산량 
```{r}
name1 <- gsub(".2", "", names(production)) # 뒤에 붙은 .1 제거
colnames(production) = c(name1)  # 제거된 .1, .4로 변경
a1 <- gather(production, key="day") # 한줄로 만들기
```

# 두개 합치기

```{r}
p <- a1$value # a1의 value를 p로 저장

production <- cbind(production2, p) # production에 생산량과 면적당을 합치기

names(production)

colnames(production) <- c("Day", "Area", "10a", "All")

production <- subset(production, production$All != "톤") # '톤' 단어 제거
production <- subset(production, production$All != "생산량") #'생산량' 단어 제거

head(production) # 데이터 확인 
```
#날씨 데이터 / 생산량 데이터
```{r}
head(weather)
head(production)

uni1 <- unique(weather$지점명)
uni2 <- unique(production$Area)
c = c()
d = c()

for (i in uni1) {
  for (j in uni2) {
    if (j == i) {
      append(c, values = i)
      append(d, values = j)
    }
    
  }
  
}
```


# 전라남도 데이터 ----------------------------------------------
```{R}
d = c('순천','영광군','목포','고흥','여수','무안','진도군','완도','해남','장흥','강진군')



z1 <- production[production$Area == '순천시', ]
z2 <- production[production$Area == '영광군', ]
z3 <- production[production$Area == '목포시', ]
z4 <- production[production$Area == '고흥군', ]
z5 <- production[production$Area == '여수시', ]
z6 <- production[production$Area == '무안군', ]
z7 <- production[production$Area == '진도군', ]
z8 <- production[production$Area == '완도군', ]
z9 <- production[production$Area == '해남군', ]
z10 <-production[production$Area == '장흥군', ]
z11 <-production[production$Area == '강진군', ]


bb <- rbind(z1,z2,z3,z4,z5,z6,z7,z8,z9,z10,z11)


# write.csv(bb,file="production.csv")


```


# 합쳐보기
```{r}
we <- read.csv("기상데이터 전처리2.csv")
pr <- read.csv("시군데이터.csv")

a1 =c("지역명", "연도") 

oh <- merge(we,pr, by=a1)

# write.csv(oh,file="통합1.csv")


```


# 충청남도 ------------------------------------------------------------
```{r}

d1 = c('천안', '대전', '보령','서산','금산','부여', '홍성')


x1 <- production[production$Area == '천안시', ]
x2 <- production[production$Area == '대전광역시']
x3 <- production[production$Area == '보령시', ]
x4 <- production[production$Area == '서산시', ]
x5 <- production[production$Area == '금산군', ]
x6 <- production[production$Area == '부여군', ]
x7 <- production[production$Area == '홍성군', ]
x8 <- production[production$Area == '대전시', ]
x9 <- production[production$Area == '보령군', ]
x10 <- production[production$Area == '서산군', ]



cnd <- rbind(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10)

# write.csv(cnd,file="시군구(충남).csv")
```


```{r}
cnd1 <- read.csv("시군구(충남).csv")
cnd2 <- read.csv("충청남도_기온.csv")

a2 = c("지역명", "연도")

cnd3 <- merge(cnd1, cnd2, by =a2)

write.csv(cnd3, "통합(충남).csv")
```



# 데이터 처리

```{r}
combine <- read.csv("통합(전라).csv")

# 첫번쨰 열 삭제

combine <- subset(combine, select = -X)
combine <- subset(combine, select = -최저해면기압.나타난날.yyyymmdd.)

str(combine)
```

## 결측치 확인
```{r}
# is.na(combine)
# 생산량의 결측치 확인
na <- combine %>% filter(is.na(생산량))
# 생산량 결측치 제거한 거
da <- combine %>% filter(!is.na(생산량))

write.csv(da, "결측치 없는거(전남).csv")
```

## 빈데이터 채워볼까
```{r}
# 연도 비교
unique(na$연도)
```
```{r}
unique(da$연도)
```
```{R}
muan0 <- na %>% filter(월 == 1) #결측치
muan1 <- da %>% filter(월 == 1) #결측치x


```


## 쌀 수확시기

수확 시기는 품종의 숙기 또는 이삭 패는 시기에 따라 다르나 중만생종 및 늦게 심은 논은 이삭 팬 후 55~60일이 수확적기이다.

일반적으로 벼 수확을 가장 많이 하는 시기는 북부 지역(한강 이북, 강원도 지역)은 9월 하순∼10월 상순, 중부지역(경기 남부, 충정도 지역)은 10월 상순∼중순, 남부 지역(영호남 지역)은 10월 중순∼하순에 주로 수확 작업을 합니다.









