---
title: "머신러닝"
author: "곽명빈"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(stringr)
library(tidyr)
library(tidyverse)
library(lubridate)
library(knitr)
library(ggplot2)
library(TTR)
library(forecast)
library(rio)
library(vars)
library(tsDyn)

```
### 데이터 불러오기
```{r}
garlic_production <- read.csv('garlic_production.csv')

```


### 시계열 분석(벡터자기회귀모형)

```{r}#
# garlic_production_ts <- ts(plz)  # 시계열 데이터로 변환

str(plz)

unique(plz$연도)

select <- dplyr::select

garlic_production_ts <- ts(plz %>% 
              select(도매가격.원.kg., 평균기온..C., 월합강수량.00.24h만..mm.),
              start = c(2015, 01),
              end = c(2021,12),
              frequency = 12)

head(garlic_production_ts)

VARselect(garlic_production_ts, lag.max=8,
            type="const")[["selection"]]

var1 <- VAR(garlic_production_ts, p=1, type="const")

var2 <- VAR(garlic_production_ts, p=2, type="const")
  serial.test(var2, lags.pt=10, type="PT.asymptotic")
  
var3 <- VAR(garlic_production_ts, p=3, type="const")
  serial.test(var3, lags.pt=10, type="PT.asymptotic")  
  
   forecast(var3) %>% 
    autoplot() 
```
## 벡터 자기회귀모형

```{r}

# str(plz)

select <- dplyr::select

garlic_production_ts <- ts(plz %>% 
              select(도매가격.원.kg.,거래량.톤.,평균기온..C.,월합강수량.00.24h만..mm.),
              start = c(2015, 01),
              end = c(2030,12),
              frequency = 12)

head(garlic_production_ts)

 
VARselect(garlic_production_ts[,1:3], lag.max=8,
type="const")[["selection"]]

var1 <- VAR(garlic_production_ts[,1:3], p=1, type="const")
serial.test(var1, lags.pt=10, type="PT.asymptotic")

var2 <- VAR(garlic_production_ts[,1:3], p=2, type="const")
serial.test(var2, lags.pt=10, type="PT.asymptotic")

var3 <- VAR(garlic_production_ts[,1:3], p=3, type="const")
serial.test(var3, lags.pt=10, type="PT.asymptotic")

forecast(var3) %>%
  autoplot() + xlab("연도")


```

## 랜덤포레스트

```{R}
library('tidyverse')
library('tidymodels')
library(randomForest)
library(yardstick)
plz <- read.csv('plz.csv')

str(plz)

plz %>%
  initial_split(prop=0.7) -> plz_split

plz_split

plz_split %>%
  training()

plz_split %>%
  testing()

str(plz)

plz$도매가격.원.kg.<-as.numeric(plz$도매가격.원.kg.)

plz$평균상대습도...<-as.numeric(plz$평균상대습도...)


plz_split %>% training() %>%
  recipe(도매가격.원.kg.~ 평균+평균기온..C.+평균상대습도...+월합강수량.00.24h만..mm.+합계.일조시간.hr.+생산량..톤.)

 plz_split %>% training() %>%
  recipe(도매가격.원.kg.~ 평균+평균기온..C.+평균상대습도...+월합강수량.00.24h만..mm.+합계.일조시간.hr.+생산량..톤.)%>%
  step_corr(all_predictors()) %>%
  step_center(all_predictors(), -all_outcomes()) %>%
  step_scale(all_predictors(), -all_outcomes()) %>%
  prep() -> plz_recipe

plz_recipe

plz_recipe %>%
  bake(plz_split %>% testing()) -> plz_testing

plz_recipe %>%
  juice() -> plz_training

plz_training

rand_forest(trees=100, mode='regression') %>%
  set_engine('randomForest') %>%
  fit(도매가격.원.kg.~ 평균+평균기온..C.+평균상대습도...+월합강수량.00.24h만..mm.+합계.일조시간.hr.+생산량..톤., data = plz_training) -> plz_rf
     
plz_rf

plz_rf %>%
  predict(plz_testing) %>%
  bind_cols(plz_testing)

a <- plz_rf %>%
  predict(plz_testing) %>%
  bind_cols(plz_testing) %>%
  metrics(truth=도매가격.원.kg., estimate=.pred)

a

```

### LSTM

```{r}






```

