---
title: "벡터자기회귀모형"
author: "곽명빈"
date: "`r Sys.Date()`"
output: html_document
---

## 라이브러리 정의
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(stringr)
library(tidyr)
library(tidyverse)
library(lubridate)
library(knitr)
library(ggplot2)
library(TTR)
library(forecast)
library(rio)
library(vars)
library(tsDyn)

```

## 벡터 자기회귀모형

```{r}
plz <- read.csv('이상치제거.csv') # 데이터 전처리 파일을 plz에 저장

#str(plz)

select <- dplyr::select # 중복함수를 피하기 위해 정의

# 시계열 데이터 변환
garlic_production_ts <- ts(plz %>% 
              select(도매가격.원.kg.,평균기온..C.,일강수량.mm.,평균.5cm.지중온도..C.,평균.풍속.m.s.,생산량..톤.),
              start = c(2015, 01),
              end = c(2020,12),
              frequency = 12)

head(garlic_production_ts)

 
VARselect(garlic_production_ts[,1:6], lag.max=8,
type="const")[["selection"]]

var1 <- VAR(garlic_production_ts[,1:6], p=1, type="const")
serial.test(var1, lags.pt=10, type="PT.asymptotic")

var2 <- VAR(garlic_production_ts[,1:6], p=2, type="const")
serial.test(var2, lags.pt=10, type="PT.asymptotic")

var3 <- VAR(garlic_production_ts[,1:6], p=3, type="const")
serial.test(var3, lags.pt=10, type="PT.asymptotic")

forecast(var3) %>%
  autoplot() + xlab("시점") 


```



